Adv_Scheduler:
  begin_epoch: 20
  max_epoch: 50
  max_value: 0.05
  name: RampScheduler
  ramp_mult: -5
Adv_Training:
  eplision: 0.03
Alpha_Scheduler:
  begin_epoch: 0
  max_epoch: 0
  min_value: 0.8
  name: RampalphaScheduler
Arch:
  name: enet
  num_classes: 4
Cot_Scheduler:
  begin_epoch: 5
  max_epoch: 50
  max_value: 0.5
  name: RampScheduler
  ramp_mult: -5
Dataset:
  augment: PILaugment
  pin_memory: false
  root_dir: !!python/object/apply:pathlib.PosixPath
  - /
  - scratch
  - ping718
  - Deep-Co-Training-for-Semi-Supervised-Image-Segmentation
  - dataset
  - ACDC-all
  subfolders:
  - img
  - gt
  transform: segment_transform((256,256))
Lab_Dataloader:
  batch_sampler:
  - PatientSampler
  - grp_regex: (patient\d+_\d+)_\d+
    shuffle: false
  batch_size: 4
  drop_last: true
  num_workers: 4
  pin_memory: false
  shuffle: true
Lab_Partitions:
  num_models: 2
  partition_overlap: 1
  partition_sets: 0.2
Loss:
  name: cross_entropy
  weight:
  - 1
  - 1
  - 1
  - 1
Optim:
  lr: 0.001
  name: Adam
  weight_decay: 0.0001
Scheduler:
  gamma: 0.1
  name: StepLR
  step_size: 90
Seed: 1233
StartTraining:
  augment_labeled_data: true
  augment_unlabeled_data: true
  save_train: false
  save_val: false
  train_adv: false
  train_jsd: false
Trainer:
  axises:
  - 1
  - 2
  - 3
  device: cuda:0
  max_epoch: 200
  metricname: metrics.csv
  save_dir: results_jsd_alpha_data0.2/baseline_p
  use_tqdm: true
Unlab_Dataloader:
  batch_size: 4
  drop_last: true
  num_workers: 4
  pin_memory: false
  shuffle: true
config: config/ACDC_config_cotraing.yaml
